/**
 * Builds the MCP Apps preview panel into a SELF-CONTAINED HTML string and writes
 * it to `server/utils/mcp/panel.generated.ts` (imported by the connector).
 *
 * Why self-contained: MCP App resources are loaded into a sandboxed iframe whose
 * HTML is the whole app. The standard, reliable pattern (and what renders in
 * claude.ai) is a single document with the JS inlined — no cross-origin script
 * fetch to depend on. We bundle the entry as an IIFE (self-executing, no module
 * exports), inline it in a <script>, and the only external resource is imghippo
 * images (whitelisted via the resource CSP).
 *
 * Run: `node mcp/build-panel.mjs` (wired to `npm run build:mcp-panel`).
 */
import { build } from "esbuild";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const result = await build({
  entryPoints: ["mcp/panel.entry.ts"],
  bundle: true,
  format: "iife", // self-executing; avoids ESM export-name issues when inlined
  minify: true,
  target: "es2020",
  legalComments: "none",
  write: false,
});

let js = result.outputFiles[0].text;
// Never allow a literal </script> to terminate our inline script tag early.
js = js.replace(/<\/script>/gi, "<\\/script>");

const html =
  `<!doctype html>` +
  `<html lang="en"><head>` +
  `<meta charset="utf-8" />` +
  `<meta name="viewport" content="width=device-width, initial-scale=1" />` +
  `<title>Case preview</title>` +
  `</head><body>` +
  `<script>${js}</script>` +
  `</body></html>`;

const out = "server/utils/mcp/panel.generated.ts";
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// AUTO-GENERATED by mcp/build-panel.mjs — do not edit by hand.\n` +
    `/* eslint-disable */\n` +
    `// prettier-ignore\n` +
    `export const PANEL_HTML = ${JSON.stringify(html)};\n`
);
console.log(`wrote ${out} (${(html.length / 1024).toFixed(0)} kB inline HTML)`);
